export const INTERESTS = [
  { id: 1, name: '강아지' },
  { id: 2, name: '고양이' },
  { id: 3, name: '물개' },
  { id: 4, name: '토끼' },
  { id: 5, name: '햄스터' },
  { id: 6, name: '앵무새' },
  { id: 7, name: '거북이' },
  { id: 8, name: '펭귄' },
  { id: 9, name: '팬더' },
  { id: 10, name: '새' },
  { id: 11, name: '야생동물' },
  { id: 12, name: '코알라' },
  { id: 13, name: '귀여움' },
  { id: 14, name: '힐링' },
  { id: 15, name: '재미' },
  { id: 16, name: '일상' },
  { id: 17, name: '감동' },
  { id: 18, name: '산책' },
] as const;
